language: python
branches:
  only:
  - master
services:
- docker
install:
- chmod +x ./scripts/test.sh
- chmod +x ./scripts/publish.sh
script:
- if [[ $TRAVIS_EVENT_TYPE == "pull_request" ]] ; then ./scripts/test.sh ; fi
- if [[ $TRAVIS_EVENT_TYPE == "push" && $TRAVIS_BRANCH == "master" ]] ; then ./scripts/publish.sh
  ; fi
notifications:
  slack:
    secure: kaQgpZjd7Oe2CN1idclKBzBTt3MPh1ziztX0vclJwPHwvycu8DKkxZBNe2bSxufb4616CFTmTOWyFO1N2DUannPitYXB3NIrk7ZGCME+DgyMGeuEgIebPwL/VaiHyggN8FdGbYHZ10lGrWLQBwi1+/KtPRRiBsY3NcS/xbd/7SnGGqGfYnE/Mv1bNxVjsJCO8TdcKIOxZKA4KDD/RZuujruecOS696w1CXuiQegrRGSS2w1rRiGdiOM3qMxz9hV8j1DaQboqGP6wKbPZtC4c595yKa3tRQWiz0GFDeXJBYXmsufhpknOGQ3gbtOHy02JAzZYwMAP/8pszumVNE8dSa0HM9OF0BjDh9GGSD4/SYk0hthHtEBH9dnwYPfNj5vRx2XPSR13ET1hyWxm872VCvZXH05iqAdVftWPvykTQdKWWWvYjR+iWGVTJY4p+LU8fOmzGwKuvUneIEIjFR4AC9TRR0z5exr6L3lQB+DzXfMsPBeNpzQiBDP4btDy034eQYRrVxT15lunlYWj+dz8HNF+Pc4lHaMS/UOSzfuguC/rwlpwT3mGOwcB5+GdD8xNVM40dNzisqnh86itfmRsyRfSED+0LFKUr2U7wZbyuM9Evb6gcuKjU3cqIyYF3dZG7oIYeWIFuHuvfsXrJjqlJJvobDDetMm1KWjKMDPMD9w=
